management:
  health:
   circuitbreakers:
    enabled: true
  endpoints:
   web:
    exposure:
     include: "*"
  endpoint:
   health:
    show-details: always
   
logging:
  file:
   name: Logs/InfoLevel.log
  level:
    root: info
   
    com.infygo.utility: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} --> %5p [%t] %c  [%M] --> %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} --> %5p [%t] %c{Class,package,method} [%M] --> %m%n"
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%X{ddd:-},%X{bp:-},%X{bpids:-}] [%X{op:-},%X{chunk:-},%X{i:-}]"

Spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/infy_go
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
      properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
 


