
Spring:
logging:
  file:
   name: Logs/InfoLevel.log
  level:
    root: info
   
    com.infygo.utility: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} --> %5p [%t] %c  [%M] --> %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} --> %5p [%t] %c{Class,package,method} [%M] --> %m%n"
Spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/infy_go
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
      properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

