spring:
logging:
  file:
   name: Customer-Loga/InfoLevel.log
  level:
    root: info
    com.infgo: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} --> %5p [%t] %c  [%M] --> %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} --> %5p [%t] %c [%M] --> %m%n"
server:
 port: 8100
