spring:
 application:
  name: movie-info-service
server:
 port: 8082
 
management:
  health:
   circuitbreakers:
    enabled: true
  endpoints:
   web:
    exposure:
     include: "*"
  endpoint:
   health:
    show-details: always
    
resilience4j:
 circuitbreaker:
   instances:
    movie-info-service:
     registerHealthIndicator: true
     eventConsumerBufferSize: 10
     failureRateThreshold: 60
     minimumNumberOfCalls: 10
     automaticTransitionFromOpenToHalfOpenEnabled: true
     waitDurationInOpenState: 3s
     permittedNumberOfCallsInHalfOpenState: 2
     slidingWindowSize: 10
     slidingWindowType: COUNT_BASED
    
#spring.cloud.config.uri: http://localhost:9999
spring.config.import: configserver:http://localhost:9999
   
 
