spring:
 application:
  name: ratings-data-service
server: 
 port: 8083

 
resilience4j:
 circuitbreaker:
   instances:
    ratings-data-service:
     registerHealthIndicator: true
     eventConsumerBufferSize: 10
     failureRateThreshold: 60
     minimumNumberOfCalls: 10
     automaticTransitionFromOpenToHalfOpenEnabled: true
     waitDurationInOpenState: 3s
     permittedNumberOfCallsInHalfOpenState: 2
     slidingWindowSize: 10
     slidingWindowType: COUNT_BASED
    
#spring.cloud.config.uri: http://localhost:9999
spring.config.import: configserver:http://localhost:9999