spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/world
  username: root
  password: root
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  properties: 
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
server:
 port: 8085
Service:
 TRAINEE_NOT_FOUND: Trainee with Given Id not found
 CLASSROOM_NOT_FOUND: Classroom not found
 CLASSROOM_FULL: Classroom is full
 Trainee_Deleted: Trainee Deleted successfully

Return: Service method returned
Trainee:
 added: Trainee Added successfully with Id : 
Classroom:
 Allocated: classroom/s allocated to given Trainee
Trainee_Deleted: Trainee deleted successfully 
